### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by kobimx** [nicholastay/node-twitch-get-stream#1]
whenever i try to use the module i get a: 

```
/root/node_modules/twitch-get-stream/index.js:136
      return cb(null, _us.compact(M3U.parse(resp)));
             ^

TypeError: cb is not a function
```

error. in fact, why do you use cb when you make a return?

**Comment by nicholastay** [comment]
Are you sure you are using the library properly? If I have not documented it properly in the README here is an example usage that I may add to it:

``` js
var twitchStreams = require('twitch-get-stream');

twitchStreams.get('channel', function(err, streams) {
    if (err) console.log('Getting streams error:', err);
    console.log('Streams successfully got, data: \n', streams);
});
```

**Comment by kobimx** [comment]
FailFish,i didn't put the js callback. working at 2AM is not a good thing. Thanks

**Comment by nicholastay** [comment]
No problem. As a side note I have updated the library to support Promises, if that interests you.
