### ISSUE TITLE
Getting error while trying to receive token

### ISSUE THREAD

**Issue by SergeyNarozhny** [nicholastay/node-twitch-get-stream#3]
http://api.twitch.tv/api/channels/ + chennel + /access_token - is not working now. Any suggestions?

**Comment by nicholastay** [comment]
Are you sure you have defined a Client ID when requiring the module? Twitch now enforces the usage of a Client ID for requests to their API, and as such it also needs to be used here.

I have actually just updated the example showing where the Client ID should be defined.

**Comment by SergeyNarozhny** [comment]
Yeah, I was using my clientID till recently, and now getting errors at the step of access_token. Is it working for you? I mean can you get any .m3u8 stream link from any channel now?

**Comment by nicholastay** [comment]
I tested it with the example script + a valid client ID and it seemed to still be able to retrieve all the m3u8 links, not sure what would be causing issues for you.

**Comment by SergeyNarozhny** [comment]
Interesting... can you provide example of code with rawParsed method (ex. channel = "dota2ruhub") ?

For ex., I use smth like:
```javascript
const clientId = '...'; //my cliendId
const twitch = require('twitch-get-stream')(clientId);

module.exports = (channel) => {
	return twitch.rawParsed(channel).then(streams => {
		return streams;
	});
}
```

**Comment by SergeyNarozhny** [comment]
Sorry, I've just found the answer. The problem was in proper handling of reject state of promise. When channel is offline, all methods return error. So handling this errors is the case.
