### ISSUE TITLE
Mixed content

### ISSUE THREAD

**Issue by az33zy** [nicholastay/node-twitch-get-stream#6]
`http://usher.twitch.tv` returns non-secure stream http URLs which causes `Mixed content` issue. Should use `https://usher.ttvnw.net` instead.

**Comment by nicholastay** [comment]
I see you've made a commit there, if you open a pr to `master` I can merge the change in for you. By the way, will this cause any side effects?

**Comment by az33zy** [comment]
Hi. I have checked and everything works fine for me. You can test it locally before merging if you want 😄

**Comment by nicholastay** [comment]
I've cherry-picked the commit into `master` and published it to `npm`, enjoy!

**Comment by az33zy** [comment]
Thanks! You're awesome! 😁
