### ISSUE TITLE
CORS request error

### ISSUE THREAD

**Issue by khanstan** [nicholastay/node-twitch-get-stream#8]
Do you have any issues with a CORS request errors? When I try to get a stream I get this error:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://api.twitch.tv/api/channels/flufflo/access_token. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`
Did something change on twitch's side?

**Comment by skyfriends** [comment]
@khanstan  We're having a similar issue.  Any chance you've figured something out?

**Comment by khanstan** [comment]
It works on 127.0.0.1. Guess this is the reason `access-control-allow-origin | https://www.twitch.tv`. 
Also the npm version of the module isn't updated with the latest commit so you should use the github version. 
Maybe it could be done by spoofing the origin using a proxy? I don't know it's not my field  :(

**Comment by nicholastay** [comment]
Sorry for the late reply, been busy - I just tested the library in node.js and it seems to work fine; so are you using the library in browser? If so, because of CORS, you may need to write a proxy on your end to get the data then pass it to the client browser.

I'm going to publish a new version today as well, changing a few internal things as well to clean up.

**Comment by azeezy** [comment]
Hello. I can get a `.m3u8` playlist, but it refuses to play in browser saying `No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://example.com' is therefore not allowed access. The response had HTTP status code 403.`

**Comment by skyfriends** [comment]
This is not an issue with the library, it should be closed Thanks @nicholastay

**Comment by nicholastay** [comment]
Will close.

As a by the way, you **cannot** play the `m3u8` playlists directly because of CORS as enforced by Twitch. This issue is the exact same problem that night's TwitchCast faced and as a result you must proxy the requests to make it function properly - quite a heavy resource hog.

**Comment by khanstan** [comment]
> Will close.
> 
> As a by the way, you **cannot** play the `m3u8` playlists directly because of CORS as enforced by Twitch. This issue is the exact same problem that night's TwitchCast faced and as a result you must proxy the requests to make it function properly - quite a heavy resource hog.

You actually can play the .m3u8 files directly. I am using your script to get the URL and then feed it to a video tag which plays just fine.
